[package]
name = "irust"
version = "1.30.5"
authors = ["Nbiba Bedis <bedisnbiba@gmail.com>"]
edition = "2018"
readme = "README.md"
description = "Cross Platform Rust Repl"
repository = "https://github.com/sigmaSd/IRust"
license = "MIT"

[dependencies]
crossterm = { version = "0.22.1", features = ["serde"] }
dirs-next = "2.0.0"
toml = "0.5.8"
serde = { version = "1.0.126", features = ["derive"] }
printer = { path = "../printer/", version = "0.3.1" }
irust_api = { path = "../irust_api/", version = "0.25.0" }
irust_repl = { path = "../irust_repl", version = "0.8.0", features = ["serde"] }
rscript = "0.14.0"

[target.'cfg(unix)'.dependencies]
nix = "0.23.0"

# flamegraph
# [profile.release]
# debug = true
